# Generated by Django 4.0.6 on 2022-07-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0002_auto_20190603_1701'),
    ]

    
